             select                                                                                                                                                                                                                                                                                                                                                                                            
                        ed.ECI_DIST_ID, ed.FLOW_ID, flo.FLOW_NAME                                                                                                                                                                                                                                                                                                                                                                                        
                        ,ed.NOREG                                                                                                                                                                                                                                                                                                                                                                                     
                        ,t.NOREG_NAME, t.DIVISION, t.DEPARTEMENT                                                                                                                                                                                                                                                                                                                                                                                        
                        ,t.SECTION
                        ,ED.ED_PE_DATA_FLAG
                        ,ED.ED_PE_STATUS                                                                                                                                                                                                                                                                                                                                                                                        
                        ,ed.PRIORITY_STATUS
                        ,eci.SYSTEM_VALUE_TXT as ECI_TYPE                                                                                                                                                                                                                             
                        ,rot.SYSTEM_VALUE_TXT as ROUTING_STATUS                                                                                                                                                                                                                                
                        ,Dsg.SYSTEM_VALUE_TXT as DESIGN_STATUS                                                                                                                                                                                                                                
                        ,pro.SYSTEM_VALUE_TXT as PROJECT_STATUS                                                                                                                                                                                                                                
                        ,imp.SYSTEM_VALUE_TXT as IMPL_STAGE_STATUS                                                                                                                                                                                                                                
                        ,cfc.SYSTEM_VALUE_TXT as CAR_FAMILY_STATUS                                                                                                                                                                                                                                
                        ,pri.SYSTEM_VALUE_TXT as PRIORITY_STATUS                                                                                                                                                                                                                                                                                                                                                                                        
                        ,ed.CREATED_BY, ed.CREATED_DT                                                                                                                                                                                                                                                                                                                                                                                        
                        ,ed.CHANGED_BY, ed.CHANGED_DT                                                                                                                                                                                                                                                                                                                                                                                       
                    from                                                                                                                                                                                                                                                                                                                                                                                            
                        TB_M_ECI_DIST ed                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_PIC t on t.NOREG = ed.NOREG                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_SYSTEM eci on eci.SYSTEM_TYPE_CD = ed.ECI_TYPE                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_SYSTEM rot on rot.SYSTEM_TYPE_CD = ed.ROUTING_STATUS                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_SYSTEM Dsg on Dsg.SYSTEM_TYPE_CD = ed.DESIGN_STATUS                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_SYSTEM pro on pro.SYSTEM_TYPE_CD = ed.PROJECT_STATUS                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_SYSTEM imp on imp.SYSTEM_TYPE_CD = ed.IMPL_STAGE_STATUS                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_SYSTEM cfc on cfc.SYSTEM_TYPE_CD = ed.CAR_FAMILY_STATUS                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_SYSTEM pri on pri.SYSTEM_TYPE_CD = ed.PRIORITY_STATUS                                                                                                                                                                                                                                                                                                                                                                                       
                        left join TB_M_FLOW flo on flo.FLOW_ID = ed.FLOW_ID 
   where                                                                                                                                                                                                                                    
    ed.ECI_DIST_ID in (                                                                                                                                                                                                                                
        select distinct ECI_DIST_ID from(                                                                                                                                                                                                                            
            select                                                                                                                                                                                                                        
                e.ECI_DIST_ID, e.FLOW_ID                                                                                                                                                                                                                    
                ,e.NOREG, t.NOREG_NAME 
                ,t.DIVISION                                                                                                                                                                                                                     
                ,t.DEPARTEMENT, t.SECTION                                                                                                                                                                                                                    
                ,d.DESIGN_ID, r.ROUTING_ID                                                                                                                                                                                                                    
                ,p.PROJECT_ID, i.IMPL_STAGE_ID                                                                                                                                                                                                                    
                ,cf.CAR_FAMILY_ID, pri.PRIORITY                                                                                                                                                                                                                    
                ,e.ECI_TYPE, e.ROUTING_STATUS                                                                                                                                                                                                                    
                ,e.DESIGN_STATUS, e.PROJECT_STATUS                                                                                                                                                                                                                    
                ,e.IMPL_STAGE_STATUS, e.CAR_FAMILY_STATUS                                                                                                                                                                                                                    
                ,e.PRIORITY_STATUS, e.ED_PE_DATA_FLAG                                                                                                                                                                                                                 
                ,e.ED_PE_STATUS, e.CREATED_BY                                                                                                                                                                                                             
                ,e.CREATED_DT, e.CHANGED_BY, e.CHANGED_DT                                                                                                                                                                                                                    
            from                                                                                                                                                                                                                        
                TB_M_ECI_DIST e                                                                                                                                                                                                                      
                left join TB_M_ECI_DIST_DESIGN d on d.ECI_DIST_ID = e.ECI_DIST_ID                                                                                                                                                                                                                    
                left join TB_M_ECI_DIST_ROUTING r on r.ECI_DIST_ID = e.ECI_DIST_ID                                                                                                                                                                                                                    
                left join TB_M_ECI_DIST_PROJECT p on p.ECI_DIST_ID = e.ECI_DIST_ID                                                                                                                                                                                                                    
                left join TB_M_ECI_DIST_IMPL_STAGE i on i.ECI_DIST_ID = e.ECI_DIST_ID                                                                                                                                                                                                                    
                left join TB_M_ECI_DIST_CAR_FAMILY cf on cf.ECI_DIST_ID = e.ECI_DIST_ID                                                                                                                                                                                                                    
                left join TB_M_ECI_DIST_PRIORITY pri on pri.ECI_DIST_ID = e.ECI_DIST_ID                                                                                                                                                                                                                    
                left join TB_M_PIC t on t.NOREG = e.NOREG                                                                                                                                                                                                                    
            where
                 d.DESIGN_ID ='15'                                                                                                                                                                                                              
                and r.ROUTING_ID = ''                                                                                                                                                                                                                   
                and p.PROJECT_ID  =''                                                                                                                                                                                                                   
                and i.IMPL_STAGE_ID  =''                                                                                                                                                                                                                    
                and cf.CAR_FAMILY_ID =''                                                                                                                                                                                                                    
                and pri.PRIORITY =''                                                                                                                                                                                                              
                and t.NOREG_NAME like ('%%')                               
                                                                                                                                                                                                                                  
                                                                                                                                                                                       
        ) a                                                                                                                                                                                                                            
    )  
    

<select id="searchCriteria" resultMap="PicDist" parameterType="co.id.fifgroup.master.domain.PicDistribution">
                   select                                                                                                                                                                                                                                                                                                                                                                                            
                        ed.ECI_DIST_ID, ed.FLOW_ID, flo.FLOW_NAME                                                                                                                                                                                                                                                                                                                                                                                        
                        ,ed.NOREG                                                                                                                                                                                                                                                                                                                                                                                     
                        ,t.NOREG_NAME, t.DIVISION, t.DEPARTEMENT                                                                                                                                                                                                                                                                                                                                                                                        
                        ,t.SECTION
                        ,ED.ED_PE_DATA_FLAG
                        ,ED.ED_PE_STATUS                                                                                                                                                                                                                                                                                                                                                                                        
                        ,ed.PRIORITY_STATUS
                        ,eci.SYSTEM_VALUE_TXT as ECI_TYPE                                                                                                                                                                                                                             
                        ,rot.SYSTEM_VALUE_TXT as ROUTING_STATUS                                                                                                                                                                                                                                
                        ,Dsg.SYSTEM_VALUE_TXT as DESIGN_STATUS                                                                                                                                                                                                                                
                        ,pro.SYSTEM_VALUE_TXT as PROJECT_STATUS                                                                                                                                                                                                                                
                        ,imp.SYSTEM_VALUE_TXT as IMPL_STAGE_STATUS                                                                                                                                                                                                                                
                        ,cfc.SYSTEM_VALUE_TXT as CAR_FAMILY_STATUS                                                                                                                                                                                                                                
                        ,pri.SYSTEM_VALUE_TXT as PRIORITY_STATUS                                                                                                                                                                                                                                                                                                                                                                                        
                        ,ed.CREATED_BY, ed.CREATED_DT                                                                                                                                                                                                                                                                                                                                                                                        
                        ,ed.CHANGED_BY, ed.CHANGED_DT                                                                                                                                                                                                                                                                                                                                                                                       
                    from                                                                                                                                                                                                                                                                                                                                                                                            
                        TB_M_ECI_DIST ed                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_PIC t on t.NOREG = ed.NOREG                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_SYSTEM eci on eci.SYSTEM_TYPE_CD = ed.ECI_TYPE                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_SYSTEM rot on rot.SYSTEM_TYPE_CD = ed.ROUTING_STATUS                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_SYSTEM Dsg on Dsg.SYSTEM_TYPE_CD = ed.DESIGN_STATUS                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_SYSTEM pro on pro.SYSTEM_TYPE_CD = ed.PROJECT_STATUS                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_SYSTEM imp on imp.SYSTEM_TYPE_CD = ed.IMPL_STAGE_STATUS                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_SYSTEM cfc on cfc.SYSTEM_TYPE_CD = ed.CAR_FAMILY_STATUS                                                                                                                                                                                                                                                                                                                                                                                        
                        left join TB_M_SYSTEM pri on pri.SYSTEM_TYPE_CD = ed.PRIORITY_STATUS                                                                                                                                                                                                                                                                                                                                                                                       
                        left join TB_M_FLOW flo on flo.FLOW_ID = ed.FLOW_ID 
   where                                                                                                                                                                                                                                    
    ed.ECI_DIST_ID in (                                                                                                                                                                                                                                
        select distinct ECI_DIST_ID from(                                                                                                                                                                                                                            
            select                                                                                                                                                                                                                        
                e.ECI_DIST_ID, e.FLOW_ID                                                                                                                                                                                                                    
                ,e.NOREG, t.NOREG_NAME 
                ,t.DIVISION                                                                                                                                                                                                                     
                ,t.DEPARTEMENT, t.SECTION                                                                                                                                                                                                                    
                ,d.DESIGN_ID, r.ROUTING_ID                                                                                                                                                                                                                    
                ,p.PROJECT_ID, i.IMPL_STAGE_ID                                                                                                                                                                                                                    
                ,cf.CAR_FAMILY_ID, pri.PRIORITY                                                                                                                                                                                                                    
                ,e.ECI_TYPE, e.ROUTING_STATUS                                                                                                                                                                                                                    
                ,e.DESIGN_STATUS, e.PROJECT_STATUS                                                                                                                                                                                                                    
                ,e.IMPL_STAGE_STATUS, e.CAR_FAMILY_STATUS                                                                                                                                                                                                                    
                ,e.PRIORITY_STATUS, e.ED_PE_DATA_FLAG                                                                                                                                                                                                                 
                ,e.ED_PE_STATUS, e.CREATED_BY                                                                                                                                                                                                             
                ,e.CREATED_DT, e.CHANGED_BY, e.CHANGED_DT                                                                                                                                                                                                                    
            from                                                                                                                                                                                                                        
                TB_M_ECI_DIST e                                                                                                                                                                                                                      
                left join TB_M_ECI_DIST_DESIGN d on d.ECI_DIST_ID = e.ECI_DIST_ID                                                                                                                                                                                                                    
                left join TB_M_ECI_DIST_ROUTING r on r.ECI_DIST_ID = e.ECI_DIST_ID                                                                                                                                                                                                                    
                left join TB_M_ECI_DIST_PROJECT p on p.ECI_DIST_ID = e.ECI_DIST_ID                                                                                                                                                                                                                    
                left join TB_M_ECI_DIST_IMPL_STAGE i on i.ECI_DIST_ID = e.ECI_DIST_ID                                                                                                                                                                                                                    
                left join TB_M_ECI_DIST_CAR_FAMILY cf on cf.ECI_DIST_ID = e.ECI_DIST_ID                                                                                                                                                                                                                    
                left join TB_M_ECI_DIST_PRIORITY pri on pri.ECI_DIST_ID = e.ECI_DIST_ID                                                                                                                                                                                                                    
                left join TB_M_PIC t on t.NOREG = e.NOREG                                                                                                                                                                                                                    
            where 1=1 
            <if test="sDesignId != null "> 
                d.DESIGN_ID  = #{sDesignId, jdbcType=VARCHAR}
            </if>  
            <if test="sDesignId == null "> 
              and d.DESIGN_ID like('%%') 
            </if>
            
            <if test="sRoutingId != null ">                                                                                                                                                                                                          
                and r.ROUTING_ID  = #{sRoutingId, jdbcType=VARCHAR}
            </if>  
            <if test="sRoutingId == null "> 
                and r.ROUTING_ID like ('%%') 
            </if> 
            
            <if test="sProjectId != null ">                                                                                                                                                                                                        
                and p.PROJECT_ID  = #{sProjectId, jdbcType=VARCHAR}
            </if>
            <if test="sProjectId == null ">   
                and p.PROJECT_ID ('%%') 
             </if>  
             
             <if test="sImplStageId != null ">                                                                                                                                                                                                                
                and i.IMPL_STAGE_ID = #{sImplStageId, jdbcType=VARCHAR}
             </if>
             <if test="sImplStageId == null ">
               and i.IMPL_STAGE_ID ('%%')
             </if>
             
              <if test="sCarFamilyId != null ">                                                                                                                                                                                                               
                and cf.CAR_FAMILY_ID =#{sCarFamilyId, jdbcType=VARCHAR}
             </if>   
             <if test="sCarFamilyId == null "> 
                  and cf.CAR_FAMILY_ID ('%%')  
             </if> 
             
             <if test="priority != null  ">                                                                                                                                                                                                         
                and pri.PRIORITY  =#{priority, jdbcType=VARCHAR}
             </if>
             <if test="priority == null ">   
                 and pri.PRIORITY  like ('%%') 
             </if>                                                                                                                                                                                                          
                and t.NOREG_NAME like upper('%' || #{noregName, jdbcType=VARCHAR} || '%')  
                                                                                                                                                                                                                         
        ) a                                                                                                                                                                                                                            
    )                  
    </select>
    
    
     