

CREATE TABLE TB_M_IMPL_STAGE
(
IMPL_STAGE_ID INT NOT NULL,
IMPL_STAGE_CD VARCHAR2(10) NOT NULL,
IMPL_STAGE_NAME VARCHAR2(100) NOT NULL,
CREATED_BY VARCHAR2(50),
CREATED_DT TIMESTAMP,
CHANGED_BY VARCHAR(50),
CHANGED_DT TIMESTAMP
);


ALTER TABLE TB_M_IMPL_STAGE
    ADD CONSTRAINT TB_M_IMPL_STAGE_PK PRIMARY KEY(IMPL_STAGE_ID);

ALTER TABLE TB_M_IMPL_STAGE
    ADD CONSTRAINT TB_M_IMPL_STAGE_AK UNIQUE(IMPL_STAGE_CD);